### ISSUE TITLE
Unable to setup 2n device

### ISSUE THREAD

**Issue by ronluna** [SVD-NL/helios2n-hass#5]
**Describe the bug**
Unable to add intercom to HA

**To Reproduce**
1. Go to settings 
2. Click on on devices
3. Click on Add Integration
4. Select 2n/Helios
5. Enter the IP, Login and Pass
6. See error

`
Unknown error occurred
`

**Expected behavior**
Finish the creation of the 2n device

**Screenshots**

**Intercom details**
Device type: *2n IP Verso*
Firmware version: 2.40.0.53.4

**Homeassistant details**
Installation type:
Version:

**Logs**
`
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/helios2n/config_flow.py:26
Integration: 2n/Helios (documentation, issues)
First occurred: 3:25:37 PM (2 occurrences)
Last logged: 3:25:43 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 296, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 392, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/helios2n/config_flow.py", line 26, in async_step_user
    await self.async_set_unique_id(device.data.serial)
                                   ^^^^^^
UnboundLocalError: cannot access local variable 'device' where it is not associated with a value

`

**Comment by Neffez** [comment]
Make sure you set the services to use unsecure connection type and basic authentication.
If it still does not work, this integration uses the [py2n](https://github.com/elektr0nisch/py2n) library, you can test the connection with that library and it will print an error, which might help to locate the issue.

**Comment by jonathanattwood** [comment]
New to HA...am seeing the same "Unknown error" at exactly the same point. Was there a resolution to this?
