### ISSUE TITLE
Added 2N IP Verso, no entities 

### ISSUE THREAD

**Issue by JohnMcGJr** [SVD-NL/helios2n-hass#6]
**Describe the bug**
Added my door intercom after setting up the API, and no entities are discovered. 

**To Reproduce**
Setup 2N IP verso API settings per documentation
Add 2N IP verso to Homeassistant with IP/user/pass
No entities are added

**Expected behavior**
Entities are added and functional

**Intercom details**
Device type:2N IP Verso
Firmware version: 2.40.0.53.4
Hardware version: 570v8

**Homeassistant details**
Installation type: Docker
Version: 2023.8.2

**Logs**
2023-08-16 11:47:54.346 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration helios2n which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-16 11:47:54.354 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-16 11:47:57.155 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://alexa-api.nabucasa.com/access_token (400)
2023-08-16 11:48:33.704 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform helios2n
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'id'
2023-08-16 11:48:33.708 ERROR (MainThread) [homeassistant.components.switch] Error while setting up helios2n platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 370, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'id'
2023-08-16 11:48:33.718 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform helios2n
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'id'
2023-08-16 11:48:33.721 ERROR (MainThread) [homeassistant.components.button] Error adding entities for domain button with platform helios2n
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'id'
2023-08-16 11:48:33.723 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up helios2n platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 370, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'id'
2023-08-16 11:48:33.726 ERROR (MainThread) [homeassistant.components.button] Error while setting up helios2n platform for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 370, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'id'

**Comment by Neffez** [comment]
I've created a PR to fix this error: https://github.com/SVD-NL/helios2n-hass/pull/7

Seems like "id" is not a supported property anymore (see https://developers.home-assistant.io/docs/device_registry_index/)

**Comment by JohnMcGJr** [comment]
Seems to work for me when I edit the files to match.

**Comment by Lux-WorldPC** [comment]
works fine for me too.     but is there no camera integration ?

**Comment by Neffez** [comment]
Just use the existing camera integrations from home assistant. MJPEG, onvif or whatever, they all work. This integration is mainly for the extra features.

**Comment by P1Rebo** [comment]
Can you merge this solution to the code?

**Comment by achecchia** [comment]
@JohnMcGJr what exactly did you change to make it work? i'm on a job site and i need to figure this out. thanks for your help.

**Comment by jzuffere** [comment]
Same issue here with my 2N Verso. Did you manage to integrate this fix? Thanks.

**Comment by captaincanada** [comment]
same issue. device stopped working. after reinstalling no entities are added just the device is showing. how can i fix this? and is it not possible to add a logo to the integration?

**Comment by ng845** [comment]
Same issue for my 2N IP Verso. Intergation works (2N access possible), but no entities available for further automations.
What exactly did you change @Neffez on Sep 15, 2023?
Thank's

**Comment by Neffez** [comment]
@ng845 You can view the changes in the fork https://github.com/Neffez/helios2n-hass
You can also add the fork as custom repository in you HACS and use the updated integration. Currently at v0.4.1

**Comment by ng845** [comment]
@Neffez Thank's. But I'm not so fimilar with HA and github. I installed helios2n-hass by HACS - custom repository, but it was v03.4.. Then I copied the individual files (source.zip) from v0.4.1 to custom/components/helios2n, restarted HA, but the integration does not work. The helios2n-hass integration (v03.4) works, but shows only 5 entities, without doorbell button entity. This "doorbell-button" sensor would be improtant for my automation.

**Comment by Neffez** [comment]
@ng845 You can install it the same way, just add my repo as custom repository and install v0.4.1.

For the doorbell: the doorbell can trigger an HTTP call, I'm not sure if it's part of the API (haven't looked into it, usually an API is for incoming requests, while the doorbell is an outgoing event). I use a rest service in my home assistant (using node red) which is called by the 2N IP Verso once the doorbell button is pressed, you don't need the integration for this. The rest service then triggers a home assistant helper button which is used in automations.

Hope this helps.

**Comment by ng845** [comment]
@Neffez Do you use the 2N gold licence for video streaming (camera stream to HA, rstp or ONIV)? Currently I'm using FritzBox and the Fritz dect phones for the camera. But I'm not able to use this picture (moving jpeg) in HA.
Thank's again for your help!

**Comment by Neffez** [comment]
@ng845 for the camera I use this integration: https://github.com/AlexxIT/WebRTC with this configuration

```
type: custom:webrtc-camera
streams:
  - url: rtsp://username:password@xxx.xxx.xxx.xx:554/h264_stream
    name: HD
    media: video,audio
  - url: http://xxx.xxx.xxx.xx/api/camera/snapshot?width=1280&height=960&fps=15
    name: SD
    media: video
style: >-
  .mode {display: none} .mode {display: none} .screenshot {display: none}
  .pictureinpicture {display: none}
ui: true
digital_ptz:
  mouse_drag_pan: true
  mouse_wheel_zoom: true
  mouse_double_click_zoom: true
  touch_drag_pan: true
  touch_pinch_zoom: true
  touch_tap_drag_zoom: true
```

The 2N Integration is only good for sensors and relays/input/output
